-- CreateTable
CREATE TABLE "clients" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "client_code" TEXT NOT NULL,
    "client_type" TEXT NOT NULL,
    "company_name" TEXT NOT NULL,
    "contact_person" TEXT NOT NULL,
    "designation" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Active',
    "lead_score" INTEGER DEFAULT 0,
    "date_added" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_updated" DATETIME NOT NULL,
    "email_primary" TEXT NOT NULL,
    "email_secondary" TEXT,
    "phone_primary" TEXT NOT NULL,
    "phone_secondary" TEXT,
    "whatsapp" TEXT,
    "website" TEXT,
    "linkedin" TEXT,
    "address_line1" TEXT,
    "address_line2" TEXT,
    "city" TEXT,
    "state_province" TEXT,
    "country" TEXT,
    "postal_code" TEXT,
    "timezone" TEXT,
    "industry" TEXT,
    "company_size" TEXT,
    "annual_revenue_estimate" REAL DEFAULT 0,
    "tax_id" TEXT,
    "business_registration_number" TEXT,
    "payment_terms_preferred" TEXT,
    "credit_limit" REAL DEFAULT 0,
    "currency_preferred" TEXT DEFAULT 'USD',
    "lead_source" TEXT,
    "lead_status" TEXT,
    "lead_temperature" TEXT,
    "probability_to_close" INTEGER DEFAULT 0,
    "expected_close_date" DATETIME,
    "expected_order_value" REAL DEFAULT 0,
    "lost_reason" TEXT,
    "competitor_name" TEXT,
    "products_interested_in" TEXT,
    "preferred_packaging" TEXT,
    "certifications_required" TEXT,
    "quality_standards" TEXT,
    "typical_order_quantity" TEXT,
    "order_frequency" TEXT,
    "total_orders" INTEGER NOT NULL DEFAULT 0,
    "total_revenue" REAL NOT NULL DEFAULT 0,
    "average_order_value" REAL NOT NULL DEFAULT 0,
    "first_order_date" DATETIME,
    "last_order_date" DATETIME,
    "days_since_last_order" INTEGER DEFAULT 0,
    "outstanding_balance" REAL NOT NULL DEFAULT 0,
    "credit_days_average" INTEGER DEFAULT 0,
    "payment_reliability_score" INTEGER DEFAULT 0,
    "last_contact_date" DATETIME,
    "last_contact_type" TEXT,
    "next_follow_up_date" DATETIME,
    "follow_up_notes" TEXT,
    "total_interactions" INTEGER NOT NULL DEFAULT 0,
    "email_open_rate" REAL DEFAULT 0,
    "response_rate" REAL DEFAULT 0,
    "notes" TEXT,
    "strengths" TEXT,
    "concerns" TEXT,
    "decision_makers" TEXT,
    "assigned_to" TEXT,
    "tags" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "clients_client_code_key" ON "clients"("client_code");
