-- CreateTable
CREATE TABLE "orders" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "order_number" TEXT NOT NULL,
    "inquiry_number" TEXT,
    "quote_number" TEXT,
    "order_type" TEXT NOT NULL,
    "order_status" TEXT NOT NULL,
    "priority" TEXT NOT NULL DEFAULT 'Medium',
    "client_id" INTEGER,
    "client_name" TEXT NOT NULL,
    "client_email" TEXT,
    "client_phone" TEXT,
    "billing_address" TEXT,
    "shipping_address" TEXT,
    "order_date" DATETIME NOT NULL,
    "inquiry_date" DATETIME,
    "quote_date" DATETIME,
    "expected_delivery_date" DATETIME,
    "actual_delivery_date" DATETIME,
    "lead_time_days" INTEGER,
    "subtotal" REAL NOT NULL DEFAULT 0,
    "tax_amount" REAL NOT NULL DEFAULT 0,
    "shipping_cost" REAL NOT NULL DEFAULT 0,
    "discount_amount" REAL NOT NULL DEFAULT 0,
    "total_amount" REAL NOT NULL DEFAULT 0,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "exchange_rate" REAL DEFAULT 1,
    "incoterm" TEXT,
    "port_of_loading" TEXT,
    "port_of_discharge" TEXT,
    "shipping_method" TEXT,
    "shipping_line" TEXT,
    "container_number" TEXT,
    "bl_number" TEXT,
    "awb_number" TEXT,
    "tracking_number" TEXT,
    "estimated_departure_date" DATETIME,
    "actual_departure_date" DATETIME,
    "estimated_arrival_date" DATETIME,
    "actual_arrival_date" DATETIME,
    "payment_terms" TEXT,
    "payment_status" TEXT NOT NULL DEFAULT 'Pending',
    "advance_percentage" REAL DEFAULT 0,
    "advance_amount" REAL DEFAULT 0,
    "advance_received_date" DATETIME,
    "balance_amount" REAL DEFAULT 0,
    "balance_received_date" DATETIME,
    "payment_method" TEXT,
    "proforma_invoice_url" TEXT,
    "commercial_invoice_url" TEXT,
    "packing_list_url" TEXT,
    "certificate_of_origin_url" TEXT,
    "phytosanitary_certificate_url" TEXT,
    "bill_of_lading_url" TEXT,
    "other_documents" TEXT,
    "assigned_to" TEXT,
    "source" TEXT,
    "notes" TEXT,
    "follow_up_date" DATETIME,
    "last_contact_date" DATETIME,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    "created_by" TEXT,
    "updated_by" TEXT
);

-- CreateTable
CREATE TABLE "order_line_items" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "order_id" INTEGER NOT NULL,
    "product_id" INTEGER,
    "product_name" TEXT NOT NULL,
    "product_code" TEXT,
    "quantity" REAL NOT NULL,
    "unit" TEXT NOT NULL,
    "unit_price" REAL NOT NULL,
    "total_price" REAL NOT NULL,
    "specifications" TEXT,
    "vendor_id" INTEGER,
    "vendor_cost" REAL DEFAULT 0,
    "margin" REAL DEFAULT 0,
    CONSTRAINT "order_line_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "orders_order_number_key" ON "orders"("order_number");
